accounts:
  - name: alice
    coins: ["1000000000000000000000atestfet", "500stake"]
  - name: bob
    coins: ["1000000000000000000000atestfet"]
validator:
  name: alice
  staked: "10000000000000000000atestfet"
# FIXME: current faucet implementation can't parse 18 decimals coins.
# faucet:
#   name: faucet
#   coins: ["1000000000000000000000atestfet"]
#   # coins_max: ["1000000000000000000atestfet"]
#   port: 4500

host:
  rpc: ":26667"
  p2p: ":26666"
  prof: ":6061"
  grpc: ":9091"
  api: ":1327"

init:
  # FETCHD_HOME (default ~/.fetchd)
  home: "/tmp/fetchd2"
  keyring-backend: "test"
  # custom config.toml
  config:
    consensus.timeout_commit: "5s"
    consensus.create_empty_blocks_interval: "5s"
  # custom app.toml
  app:

# custom genesis
genesis:
  chain_id: "testnet-2"
  app_state:
    staking:
      params:
        bond_denom: "atestfet"
    mint:
      params:
        mint_denom: "atestfet"

build:
  binary: fetchd
