// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: fetchai/blsgroup/v1/tx.proto

package blsgroup

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/codec/types"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	group "github.com/cosmos/cosmos-sdk/x/group"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgRegisterBlsGroup struct {
	// admin is the current account address of the group admin.
	Admin string `protobuf:"bytes,1,opt,name=admin,proto3" json:"admin,omitempty"`
	// group_id is the group ID to register as a BLS group.
	GroupId uint64 `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
}

func (m *MsgRegisterBlsGroup) Reset()         { *m = MsgRegisterBlsGroup{} }
func (m *MsgRegisterBlsGroup) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterBlsGroup) ProtoMessage()    {}
func (*MsgRegisterBlsGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e5efa1b539f0d6e, []int{0}
}
func (m *MsgRegisterBlsGroup) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterBlsGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterBlsGroup.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterBlsGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterBlsGroup.Merge(m, src)
}
func (m *MsgRegisterBlsGroup) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterBlsGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterBlsGroup.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterBlsGroup proto.InternalMessageInfo

func (m *MsgRegisterBlsGroup) GetAdmin() string {
	if m != nil {
		return m.Admin
	}
	return ""
}

func (m *MsgRegisterBlsGroup) GetGroupId() uint64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

type MsgRegisterBlsGroupResponse struct {
}

func (m *MsgRegisterBlsGroupResponse) Reset()         { *m = MsgRegisterBlsGroupResponse{} }
func (m *MsgRegisterBlsGroupResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterBlsGroupResponse) ProtoMessage()    {}
func (*MsgRegisterBlsGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e5efa1b539f0d6e, []int{1}
}
func (m *MsgRegisterBlsGroupResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterBlsGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterBlsGroupResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterBlsGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterBlsGroupResponse.Merge(m, src)
}
func (m *MsgRegisterBlsGroupResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterBlsGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterBlsGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterBlsGroupResponse proto.InternalMessageInfo

type MsgUnregisterBlsGroup struct {
	// admin is the current account address of the group admin.
	Admin string `protobuf:"bytes,1,opt,name=admin,proto3" json:"admin,omitempty"`
	// group_id is the group ID to unregister.
	GroupId uint64 `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
}

func (m *MsgUnregisterBlsGroup) Reset()         { *m = MsgUnregisterBlsGroup{} }
func (m *MsgUnregisterBlsGroup) String() string { return proto.CompactTextString(m) }
func (*MsgUnregisterBlsGroup) ProtoMessage()    {}
func (*MsgUnregisterBlsGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e5efa1b539f0d6e, []int{2}
}
func (m *MsgUnregisterBlsGroup) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUnregisterBlsGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUnregisterBlsGroup.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUnregisterBlsGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUnregisterBlsGroup.Merge(m, src)
}
func (m *MsgUnregisterBlsGroup) XXX_Size() int {
	return m.Size()
}
func (m *MsgUnregisterBlsGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUnregisterBlsGroup.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUnregisterBlsGroup proto.InternalMessageInfo

func (m *MsgUnregisterBlsGroup) GetAdmin() string {
	if m != nil {
		return m.Admin
	}
	return ""
}

func (m *MsgUnregisterBlsGroup) GetGroupId() uint64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

type MsgUnregisterBlsGroupResponse struct {
}

func (m *MsgUnregisterBlsGroupResponse) Reset()         { *m = MsgUnregisterBlsGroupResponse{} }
func (m *MsgUnregisterBlsGroupResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUnregisterBlsGroupResponse) ProtoMessage()    {}
func (*MsgUnregisterBlsGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e5efa1b539f0d6e, []int{3}
}
func (m *MsgUnregisterBlsGroupResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUnregisterBlsGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUnregisterBlsGroupResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUnregisterBlsGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUnregisterBlsGroupResponse.Merge(m, src)
}
func (m *MsgUnregisterBlsGroupResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUnregisterBlsGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUnregisterBlsGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUnregisterBlsGroupResponse proto.InternalMessageInfo

// MsgVote is the Msg/Vote request type.
type MsgVote struct {
	// proposal is the unique ID of the proposal.
	ProposalId uint64 `protobuf:"varint,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	// voter is the voter account address.
	Voter string `protobuf:"bytes,2,opt,name=voter,proto3" json:"voter,omitempty"`
	// option is the voter's choice on the proposal.
	Option group.VoteOption `protobuf:"varint,3,opt,name=option,proto3,enum=cosmos.group.v1.VoteOption" json:"option,omitempty"`
	// timeout_height set a block timeout height to prevent the vote from being used past a certain height.
	// Voters must not issue new votes until their previous vote has expired to prevent
	// swapping them when aggregating.
	TimeoutHeight int64 `protobuf:"varint,4,opt,name=timeout_height,json=timeoutHeight,proto3" json:"timeout_height,omitempty"`
}

func (m *MsgVote) Reset()         { *m = MsgVote{} }
func (m *MsgVote) String() string { return proto.CompactTextString(m) }
func (*MsgVote) ProtoMessage()    {}
func (*MsgVote) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e5efa1b539f0d6e, []int{4}
}
func (m *MsgVote) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgVote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgVote.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgVote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgVote.Merge(m, src)
}
func (m *MsgVote) XXX_Size() int {
	return m.Size()
}
func (m *MsgVote) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgVote.DiscardUnknown(m)
}

var xxx_messageInfo_MsgVote proto.InternalMessageInfo

func (m *MsgVote) GetProposalId() uint64 {
	if m != nil {
		return m.ProposalId
	}
	return 0
}

func (m *MsgVote) GetVoter() string {
	if m != nil {
		return m.Voter
	}
	return ""
}

func (m *MsgVote) GetOption() group.VoteOption {
	if m != nil {
		return m.Option
	}
	return group.VOTE_OPTION_UNSPECIFIED
}

func (m *MsgVote) GetTimeoutHeight() int64 {
	if m != nil {
		return m.TimeoutHeight
	}
	return 0
}

type MsgVoteResponse struct {
	// proposal is the unique ID of the proposal.
	ProposalId uint64 `protobuf:"varint,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	// voter is the voter account address.
	Voter string `protobuf:"bytes,2,opt,name=voter,proto3" json:"voter,omitempty"`
	// option is the voter's choice on the proposal.
	Option group.VoteOption `protobuf:"varint,3,opt,name=option,proto3,enum=cosmos.group.v1.VoteOption" json:"option,omitempty"`
	// pub_key is the voter's public key.
	PubKey *types.Any `protobuf:"bytes,4,opt,name=pub_key,json=pubKey,proto3" json:"public_key,omitempty"`
	// sig is the individual signature which will be aggregated with other signatures.
	Sig []byte `protobuf:"bytes,5,opt,name=sig,proto3" json:"sig,omitempty"`
	// timeout_height is a block timeout height to prevent the vote from being used past a certain height.
	TimeoutHeight int64 `protobuf:"varint,6,opt,name=timeout_height,json=timeoutHeight,proto3" json:"timeout_height,omitempty"`
}

func (m *MsgVoteResponse) Reset()         { *m = MsgVoteResponse{} }
func (m *MsgVoteResponse) String() string { return proto.CompactTextString(m) }
func (*MsgVoteResponse) ProtoMessage()    {}
func (*MsgVoteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e5efa1b539f0d6e, []int{5}
}
func (m *MsgVoteResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgVoteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgVoteResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgVoteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgVoteResponse.Merge(m, src)
}
func (m *MsgVoteResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgVoteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgVoteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgVoteResponse proto.InternalMessageInfo

func (m *MsgVoteResponse) GetProposalId() uint64 {
	if m != nil {
		return m.ProposalId
	}
	return 0
}

func (m *MsgVoteResponse) GetVoter() string {
	if m != nil {
		return m.Voter
	}
	return ""
}

func (m *MsgVoteResponse) GetOption() group.VoteOption {
	if m != nil {
		return m.Option
	}
	return group.VOTE_OPTION_UNSPECIFIED
}

func (m *MsgVoteResponse) GetPubKey() *types.Any {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *MsgVoteResponse) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

func (m *MsgVoteResponse) GetTimeoutHeight() int64 {
	if m != nil {
		return m.TimeoutHeight
	}
	return 0
}

// MsgVoteAgg is the Msg/VoteAgg request type.
type MsgVoteAgg struct {
	// sender is the account address who submits the votes.
	Sender string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	// proposal is the unique ID of the proposal.
	ProposalId uint64 `protobuf:"varint,2,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	// votes are the list of voters' choices on the proposal.
	Votes []group.VoteOption `protobuf:"varint,3,rep,packed,name=votes,proto3,enum=cosmos.group.v1.VoteOption" json:"votes,omitempty"`
	// agg_sig is the bls aggregated signature for all the votes.
	AggSig []byte `protobuf:"bytes,4,opt,name=agg_sig,json=aggSig,proto3" json:"agg_sig,omitempty"`
	// exec defines whether the proposal should be executed.
	// immediately after voting or not.
	Exec group.Exec `protobuf:"varint,5,opt,name=exec,proto3,enum=cosmos.group.v1.Exec" json:"exec,omitempty"`
	// timeout_height is a block timeout height to prevent the votes from being used past a certain height
	// all aggregated votes must share the same timeout_height in order to verify the aggregated signature.
	TimeoutHeight int64 `protobuf:"varint,6,opt,name=timeout_height,json=timeoutHeight,proto3" json:"timeout_height,omitempty"`
}

func (m *MsgVoteAgg) Reset()         { *m = MsgVoteAgg{} }
func (m *MsgVoteAgg) String() string { return proto.CompactTextString(m) }
func (*MsgVoteAgg) ProtoMessage()    {}
func (*MsgVoteAgg) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e5efa1b539f0d6e, []int{6}
}
func (m *MsgVoteAgg) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgVoteAgg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgVoteAgg.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgVoteAgg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgVoteAgg.Merge(m, src)
}
func (m *MsgVoteAgg) XXX_Size() int {
	return m.Size()
}
func (m *MsgVoteAgg) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgVoteAgg.DiscardUnknown(m)
}

var xxx_messageInfo_MsgVoteAgg proto.InternalMessageInfo

func (m *MsgVoteAgg) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgVoteAgg) GetProposalId() uint64 {
	if m != nil {
		return m.ProposalId
	}
	return 0
}

func (m *MsgVoteAgg) GetVotes() []group.VoteOption {
	if m != nil {
		return m.Votes
	}
	return nil
}

func (m *MsgVoteAgg) GetAggSig() []byte {
	if m != nil {
		return m.AggSig
	}
	return nil
}

func (m *MsgVoteAgg) GetExec() group.Exec {
	if m != nil {
		return m.Exec
	}
	return group.Exec_EXEC_UNSPECIFIED
}

func (m *MsgVoteAgg) GetTimeoutHeight() int64 {
	if m != nil {
		return m.TimeoutHeight
	}
	return 0
}

// MsgVoteResponse is the Msg/Vote response type.
type MsgVoteAggResponse struct {
}

func (m *MsgVoteAggResponse) Reset()         { *m = MsgVoteAggResponse{} }
func (m *MsgVoteAggResponse) String() string { return proto.CompactTextString(m) }
func (*MsgVoteAggResponse) ProtoMessage()    {}
func (*MsgVoteAggResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e5efa1b539f0d6e, []int{7}
}
func (m *MsgVoteAggResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgVoteAggResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgVoteAggResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgVoteAggResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgVoteAggResponse.Merge(m, src)
}
func (m *MsgVoteAggResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgVoteAggResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgVoteAggResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgVoteAggResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgRegisterBlsGroup)(nil), "fetchai.blsgroup.v1.MsgRegisterBlsGroup")
	proto.RegisterType((*MsgRegisterBlsGroupResponse)(nil), "fetchai.blsgroup.v1.MsgRegisterBlsGroupResponse")
	proto.RegisterType((*MsgUnregisterBlsGroup)(nil), "fetchai.blsgroup.v1.MsgUnregisterBlsGroup")
	proto.RegisterType((*MsgUnregisterBlsGroupResponse)(nil), "fetchai.blsgroup.v1.MsgUnregisterBlsGroupResponse")
	proto.RegisterType((*MsgVote)(nil), "fetchai.blsgroup.v1.MsgVote")
	proto.RegisterType((*MsgVoteResponse)(nil), "fetchai.blsgroup.v1.MsgVoteResponse")
	proto.RegisterType((*MsgVoteAgg)(nil), "fetchai.blsgroup.v1.MsgVoteAgg")
	proto.RegisterType((*MsgVoteAggResponse)(nil), "fetchai.blsgroup.v1.MsgVoteAggResponse")
}

func init() { proto.RegisterFile("fetchai/blsgroup/v1/tx.proto", fileDescriptor_4e5efa1b539f0d6e) }

var fileDescriptor_4e5efa1b539f0d6e = []byte{
	// 672 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x95, 0x31, 0x6f, 0xd3, 0x40,
	0x14, 0xc7, 0xeb, 0x24, 0x4d, 0xe0, 0x15, 0x4a, 0x75, 0x4d, 0xa9, 0x9b, 0x52, 0x27, 0x8a, 0x40,
	0x84, 0x0a, 0x6c, 0x9a, 0x6e, 0x0c, 0x48, 0x8d, 0x84, 0x4a, 0x85, 0x22, 0x24, 0x57, 0x30, 0xb0,
	0x44, 0x76, 0x7c, 0xbd, 0x9c, 0x88, 0x7d, 0x27, 0xdf, 0xb9, 0x4a, 0x56, 0x3e, 0x01, 0x5f, 0x82,
	0x9d, 0x81, 0x0f, 0x80, 0x98, 0x18, 0x2b, 0x26, 0x26, 0x84, 0x9a, 0x01, 0x89, 0x4f, 0x81, 0x7c,
	0x3e, 0xa7, 0x52, 0x93, 0xd2, 0x4e, 0x88, 0x29, 0xbe, 0xfb, 0xff, 0xee, 0xbd, 0xf7, 0x7f, 0x79,
	0xf6, 0xc1, 0x9d, 0x23, 0x2c, 0xfb, 0x03, 0x8f, 0x3a, 0xfe, 0x50, 0x90, 0x98, 0x25, 0xdc, 0x39,
	0xde, 0x71, 0xe4, 0xc8, 0xe6, 0x31, 0x93, 0x0c, 0xad, 0x6a, 0xd5, 0xce, 0x55, 0xfb, 0x78, 0xa7,
	0x56, 0x25, 0x8c, 0x30, 0xa5, 0x3b, 0xe9, 0x53, 0x86, 0xd6, 0x2c, 0xc2, 0x18, 0x19, 0x62, 0x47,
	0xad, 0xfc, 0xe4, 0xc8, 0x09, 0x92, 0xd8, 0x93, 0x94, 0x45, 0x5a, 0xaf, 0x9f, 0xd7, 0x25, 0x0d,
	0xb1, 0x90, 0x5e, 0xc8, 0x35, 0xb0, 0xd1, 0x67, 0x22, 0x64, 0xa2, 0x97, 0x45, 0xce, 0x16, 0xb9,
	0x74, 0xfe, 0xac, 0x17, 0x8d, 0xb5, 0xb4, 0x99, 0x81, 0xce, 0x59, 0xed, 0x63, 0x8e, 0xf3, 0x73,
	0xe6, 0x8c, 0xa8, 0x8d, 0xd5, 0xd6, 0xb5, 0x12, 0x0a, 0x92, 0xee, 0x87, 0x82, 0x64, 0x42, 0x73,
	0x08, 0xab, 0x5d, 0x41, 0x5c, 0x4c, 0xa8, 0x90, 0x38, 0xee, 0x0c, 0xc5, 0x7e, 0x7a, 0x16, 0xd9,
	0xb0, 0xe8, 0x05, 0x21, 0x8d, 0x4c, 0xa3, 0x61, 0xb4, 0xae, 0x77, 0xcc, 0x6f, 0x9f, 0x1e, 0x55,
	0x75, 0x89, 0x7b, 0x41, 0x10, 0x63, 0x21, 0x0e, 0x65, 0x4c, 0x23, 0xe2, 0x66, 0x18, 0xda, 0x80,
	0x6b, 0x2a, 0x69, 0x8f, 0x06, 0x66, 0xa1, 0x61, 0xb4, 0x4a, 0x6e, 0x45, 0xad, 0x0f, 0x82, 0x27,
	0xf0, 0xee, 0xd7, 0xc7, 0xed, 0x0c, 0x6b, 0x6e, 0xc1, 0xe6, 0x9c, 0x6c, 0x2e, 0x16, 0x9c, 0x45,
	0x02, 0x37, 0x23, 0x58, 0xeb, 0x0a, 0xf2, 0x2a, 0x8a, 0xff, 0x51, 0x39, 0x75, 0xd8, 0x9a, 0x9b,
	0x6f, 0x5a, 0xd0, 0x17, 0x03, 0x2a, 0x5d, 0x41, 0x5e, 0x33, 0x89, 0x51, 0x1d, 0x96, 0x78, 0xcc,
	0x38, 0x13, 0xde, 0x30, 0x0d, 0x6b, 0xa8, 0xb0, 0x90, 0x6f, 0x1d, 0x04, 0x69, 0x91, 0xc7, 0x4c,
	0xe2, 0x58, 0x65, 0xfc, 0x6b, 0x91, 0x0a, 0x43, 0xbb, 0x50, 0x66, 0x3c, 0x9d, 0x18, 0xb3, 0xd8,
	0x30, 0x5a, 0xcb, 0xed, 0x4d, 0x5b, 0xd3, 0xf9, 0xe4, 0xd9, 0x69, 0xde, 0x97, 0x0a, 0x71, 0x35,
	0x8a, 0xee, 0xc1, 0x72, 0x3a, 0x48, 0x2c, 0x91, 0xbd, 0x01, 0xa6, 0x64, 0x20, 0xcd, 0x52, 0xc3,
	0x68, 0x15, 0xdd, 0x9b, 0x7a, 0xf7, 0xb9, 0xda, 0xd4, 0x2e, 0x55, 0x9e, 0xe6, 0x87, 0x02, 0xdc,
	0xd2, 0x26, 0x72, 0x63, 0xff, 0x89, 0x99, 0x7d, 0xa8, 0xf0, 0xc4, 0xef, 0xbd, 0xc5, 0x63, 0xe5,
	0x62, 0xa9, 0x5d, 0xb5, 0xb3, 0xc9, 0xb7, 0xf3, 0xc9, 0xb7, 0xf7, 0xa2, 0x71, 0xc7, 0xfc, 0xfd,
	0xa3, 0x5e, 0xe5, 0x89, 0x3f, 0xa4, 0xfd, 0x94, 0x7d, 0xc8, 0x42, 0x2a, 0x71, 0xc8, 0xe5, 0xd8,
	0x2d, 0xf3, 0xc4, 0x7f, 0x81, 0xc7, 0x68, 0x05, 0x8a, 0x82, 0x12, 0x73, 0xb1, 0x61, 0xb4, 0x6e,
	0xb8, 0xe9, 0xe3, 0x9c, 0x3e, 0x95, 0x2f, 0xeb, 0xd3, 0xc4, 0x00, 0xd0, 0x7d, 0xda, 0x23, 0x04,
	0xdd, 0x86, 0xb2, 0xc0, 0x51, 0x80, 0xe3, 0x6c, 0xe8, 0x5c, 0xbd, 0x3a, 0xdf, 0xba, 0xc2, 0x4c,
	0xeb, 0x76, 0xb2, 0xd6, 0x09, 0xb3, 0xd8, 0x28, 0x5e, 0xd6, 0x89, 0x8c, 0x44, 0xeb, 0x50, 0xf1,
	0x08, 0xe9, 0xa5, 0x1e, 0x4a, 0xca, 0x43, 0xd9, 0x23, 0xe4, 0x90, 0x12, 0xf4, 0x00, 0x4a, 0x78,
	0x84, 0xfb, 0xca, 0xd9, 0x72, 0x7b, 0x6d, 0x26, 0xd4, 0xb3, 0x11, 0xee, 0xbb, 0x0a, 0xb9, 0xa2,
	0xe3, 0x66, 0x15, 0xd0, 0x99, 0xc9, 0x7c, 0x1e, 0xda, 0x9f, 0x0b, 0x50, 0xec, 0x0a, 0x82, 0x22,
	0x58, 0x99, 0xf9, 0x16, 0xb4, 0xec, 0x39, 0x5f, 0x45, 0x7b, 0xce, 0x7b, 0x5c, 0x7b, 0x7c, 0x55,
	0x72, 0x3a, 0x87, 0x12, 0xd0, 0x9c, 0xd7, 0x7d, 0xfb, 0xa2, 0x38, 0xb3, 0x6c, 0xad, 0x7d, 0x75,
	0x76, 0x9a, 0xf5, 0x10, 0x2a, 0xf9, 0xbf, 0x5c, 0xbf, 0xe8, 0xb8, 0x06, 0x6a, 0xf7, 0x2f, 0x01,
	0xf2, 0xa0, 0x9d, 0xa7, 0x5f, 0x4f, 0x2d, 0xe3, 0xe4, 0xd4, 0x32, 0x7e, 0x9e, 0x5a, 0xc6, 0xfb,
	0x89, 0xb5, 0x70, 0x32, 0xb1, 0x16, 0xbe, 0x4f, 0xac, 0x85, 0x37, 0x77, 0x09, 0x95, 0x83, 0xc4,
	0xb7, 0xfb, 0x2c, 0x74, 0xf2, 0xeb, 0x47, 0xfd, 0x06, 0xce, 0x68, 0x7a, 0x0f, 0xf9, 0x65, 0x35,
	0xf3, 0xbb, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x4b, 0xa3, 0x0e, 0xa3, 0xa2, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// RegisterBlsGroup checks that all group members have a bls key, and they proven possession of the corresponding private key.
	// It then register the groupID as a bls group to enable the other BLS feature (such as VoteAgg).
	RegisterBlsGroup(ctx context.Context, in *MsgRegisterBlsGroup, opts ...grpc.CallOption) (*MsgRegisterBlsGroupResponse, error)
	// UnregisterBlsGroup delete a BLS group registration
	UnregisterBlsGroup(ctx context.Context, in *MsgUnregisterBlsGroup, opts ...grpc.CallOption) (*MsgUnregisterBlsGroupResponse, error)
	// VoteAgg allows a sender to submit a set of votes
	VoteAgg(ctx context.Context, in *MsgVoteAgg, opts ...grpc.CallOption) (*MsgVoteAggResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) RegisterBlsGroup(ctx context.Context, in *MsgRegisterBlsGroup, opts ...grpc.CallOption) (*MsgRegisterBlsGroupResponse, error) {
	out := new(MsgRegisterBlsGroupResponse)
	err := c.cc.Invoke(ctx, "/fetchai.blsgroup.v1.Msg/RegisterBlsGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UnregisterBlsGroup(ctx context.Context, in *MsgUnregisterBlsGroup, opts ...grpc.CallOption) (*MsgUnregisterBlsGroupResponse, error) {
	out := new(MsgUnregisterBlsGroupResponse)
	err := c.cc.Invoke(ctx, "/fetchai.blsgroup.v1.Msg/UnregisterBlsGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) VoteAgg(ctx context.Context, in *MsgVoteAgg, opts ...grpc.CallOption) (*MsgVoteAggResponse, error) {
	out := new(MsgVoteAggResponse)
	err := c.cc.Invoke(ctx, "/fetchai.blsgroup.v1.Msg/VoteAgg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// RegisterBlsGroup checks that all group members have a bls key, and they proven possession of the corresponding private key.
	// It then register the groupID as a bls group to enable the other BLS feature (such as VoteAgg).
	RegisterBlsGroup(context.Context, *MsgRegisterBlsGroup) (*MsgRegisterBlsGroupResponse, error)
	// UnregisterBlsGroup delete a BLS group registration
	UnregisterBlsGroup(context.Context, *MsgUnregisterBlsGroup) (*MsgUnregisterBlsGroupResponse, error)
	// VoteAgg allows a sender to submit a set of votes
	VoteAgg(context.Context, *MsgVoteAgg) (*MsgVoteAggResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) RegisterBlsGroup(ctx context.Context, req *MsgRegisterBlsGroup) (*MsgRegisterBlsGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterBlsGroup not implemented")
}
func (*UnimplementedMsgServer) UnregisterBlsGroup(ctx context.Context, req *MsgUnregisterBlsGroup) (*MsgUnregisterBlsGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnregisterBlsGroup not implemented")
}
func (*UnimplementedMsgServer) VoteAgg(ctx context.Context, req *MsgVoteAgg) (*MsgVoteAggResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VoteAgg not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_RegisterBlsGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterBlsGroup)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterBlsGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fetchai.blsgroup.v1.Msg/RegisterBlsGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterBlsGroup(ctx, req.(*MsgRegisterBlsGroup))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UnregisterBlsGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUnregisterBlsGroup)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UnregisterBlsGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fetchai.blsgroup.v1.Msg/UnregisterBlsGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UnregisterBlsGroup(ctx, req.(*MsgUnregisterBlsGroup))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_VoteAgg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgVoteAgg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).VoteAgg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fetchai.blsgroup.v1.Msg/VoteAgg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).VoteAgg(ctx, req.(*MsgVoteAgg))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fetchai.blsgroup.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterBlsGroup",
			Handler:    _Msg_RegisterBlsGroup_Handler,
		},
		{
			MethodName: "UnregisterBlsGroup",
			Handler:    _Msg_UnregisterBlsGroup_Handler,
		},
		{
			MethodName: "VoteAgg",
			Handler:    _Msg_VoteAgg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fetchai/blsgroup/v1/tx.proto",
}

func (m *MsgRegisterBlsGroup) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterBlsGroup) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterBlsGroup) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.GroupId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.GroupId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Admin) > 0 {
		i -= len(m.Admin)
		copy(dAtA[i:], m.Admin)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Admin)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRegisterBlsGroupResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterBlsGroupResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterBlsGroupResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUnregisterBlsGroup) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUnregisterBlsGroup) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUnregisterBlsGroup) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.GroupId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.GroupId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Admin) > 0 {
		i -= len(m.Admin)
		copy(dAtA[i:], m.Admin)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Admin)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUnregisterBlsGroupResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUnregisterBlsGroupResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUnregisterBlsGroupResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgVote) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgVote) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgVote) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TimeoutHeight != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.TimeoutHeight))
		i--
		dAtA[i] = 0x20
	}
	if m.Option != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Option))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Voter) > 0 {
		i -= len(m.Voter)
		copy(dAtA[i:], m.Voter)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Voter)))
		i--
		dAtA[i] = 0x12
	}
	if m.ProposalId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ProposalId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgVoteResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgVoteResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgVoteResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TimeoutHeight != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.TimeoutHeight))
		i--
		dAtA[i] = 0x30
	}
	if len(m.Sig) > 0 {
		i -= len(m.Sig)
		copy(dAtA[i:], m.Sig)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sig)))
		i--
		dAtA[i] = 0x2a
	}
	if m.PubKey != nil {
		{
			size, err := m.PubKey.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.Option != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Option))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Voter) > 0 {
		i -= len(m.Voter)
		copy(dAtA[i:], m.Voter)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Voter)))
		i--
		dAtA[i] = 0x12
	}
	if m.ProposalId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ProposalId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgVoteAgg) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgVoteAgg) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgVoteAgg) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TimeoutHeight != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.TimeoutHeight))
		i--
		dAtA[i] = 0x30
	}
	if m.Exec != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Exec))
		i--
		dAtA[i] = 0x28
	}
	if len(m.AggSig) > 0 {
		i -= len(m.AggSig)
		copy(dAtA[i:], m.AggSig)
		i = encodeVarintTx(dAtA, i, uint64(len(m.AggSig)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Votes) > 0 {
		dAtA3 := make([]byte, len(m.Votes)*10)
		var j2 int
		for _, num := range m.Votes {
			for num >= 1<<7 {
				dAtA3[j2] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j2++
			}
			dAtA3[j2] = uint8(num)
			j2++
		}
		i -= j2
		copy(dAtA[i:], dAtA3[:j2])
		i = encodeVarintTx(dAtA, i, uint64(j2))
		i--
		dAtA[i] = 0x1a
	}
	if m.ProposalId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ProposalId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgVoteAggResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgVoteAggResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgVoteAggResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgRegisterBlsGroup) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Admin)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.GroupId != 0 {
		n += 1 + sovTx(uint64(m.GroupId))
	}
	return n
}

func (m *MsgRegisterBlsGroupResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUnregisterBlsGroup) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Admin)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.GroupId != 0 {
		n += 1 + sovTx(uint64(m.GroupId))
	}
	return n
}

func (m *MsgUnregisterBlsGroupResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgVote) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ProposalId != 0 {
		n += 1 + sovTx(uint64(m.ProposalId))
	}
	l = len(m.Voter)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Option != 0 {
		n += 1 + sovTx(uint64(m.Option))
	}
	if m.TimeoutHeight != 0 {
		n += 1 + sovTx(uint64(m.TimeoutHeight))
	}
	return n
}

func (m *MsgVoteResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ProposalId != 0 {
		n += 1 + sovTx(uint64(m.ProposalId))
	}
	l = len(m.Voter)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Option != 0 {
		n += 1 + sovTx(uint64(m.Option))
	}
	if m.PubKey != nil {
		l = m.PubKey.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Sig)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.TimeoutHeight != 0 {
		n += 1 + sovTx(uint64(m.TimeoutHeight))
	}
	return n
}

func (m *MsgVoteAgg) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.ProposalId != 0 {
		n += 1 + sovTx(uint64(m.ProposalId))
	}
	if len(m.Votes) > 0 {
		l = 0
		for _, e := range m.Votes {
			l += sovTx(uint64(e))
		}
		n += 1 + sovTx(uint64(l)) + l
	}
	l = len(m.AggSig)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Exec != 0 {
		n += 1 + sovTx(uint64(m.Exec))
	}
	if m.TimeoutHeight != 0 {
		n += 1 + sovTx(uint64(m.TimeoutHeight))
	}
	return n
}

func (m *MsgVoteAggResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgRegisterBlsGroup) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterBlsGroup: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterBlsGroup: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Admin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Admin = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GroupId", wireType)
			}
			m.GroupId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GroupId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterBlsGroupResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterBlsGroupResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterBlsGroupResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUnregisterBlsGroup) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUnregisterBlsGroup: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUnregisterBlsGroup: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Admin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Admin = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GroupId", wireType)
			}
			m.GroupId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GroupId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUnregisterBlsGroupResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUnregisterBlsGroupResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUnregisterBlsGroupResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgVote) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgVote: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgVote: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProposalId", wireType)
			}
			m.ProposalId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProposalId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Voter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Voter = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Option", wireType)
			}
			m.Option = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Option |= group.VoteOption(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeoutHeight", wireType)
			}
			m.TimeoutHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TimeoutHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgVoteResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgVoteResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgVoteResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProposalId", wireType)
			}
			m.ProposalId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProposalId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Voter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Voter = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Option", wireType)
			}
			m.Option = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Option |= group.VoteOption(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PubKey", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.PubKey == nil {
				m.PubKey = &types.Any{}
			}
			if err := m.PubKey.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sig", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sig = append(m.Sig[:0], dAtA[iNdEx:postIndex]...)
			if m.Sig == nil {
				m.Sig = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeoutHeight", wireType)
			}
			m.TimeoutHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TimeoutHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgVoteAgg) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgVoteAgg: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgVoteAgg: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProposalId", wireType)
			}
			m.ProposalId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProposalId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType == 0 {
				var v group.VoteOption
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTx
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= group.VoteOption(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Votes = append(m.Votes, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTx
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthTx
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthTx
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				if elementCount != 0 && len(m.Votes) == 0 {
					m.Votes = make([]group.VoteOption, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v group.VoteOption
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowTx
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= group.VoteOption(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Votes = append(m.Votes, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Votes", wireType)
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AggSig", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AggSig = append(m.AggSig[:0], dAtA[iNdEx:postIndex]...)
			if m.AggSig == nil {
				m.AggSig = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Exec", wireType)
			}
			m.Exec = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Exec |= group.Exec(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeoutHeight", wireType)
			}
			m.TimeoutHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TimeoutHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgVoteAggResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgVoteAggResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgVoteAggResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
