name: 🐛 Bug Report
description: Report a reproducible bug.
title: "Bug report: <short description>"
labels: ["bug", "unconfirmed"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting the issue you are facing. Please complete the following so we can have the details necessary to assist you.
  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm before submitting a new issue
      options:
        - label: I am running the [latest fetchd version](https://docs.fetch.ai/ledger_v2/versions/).
          required: true
        - label: I checked the [documentation](https://docs.fetch.ai/ledger_v2/cli-introduction/) and found no answer to my problem.
          required: true
        - label: I checked the [existing issues](https://github.com/fetchai/fetchd/issues) to make sure my problem has not already been reported.
          required: true
  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Select the category that best describes the bug.
      options:
        - Bug (unexpected behavior)
        - Documentation Issue (error or unclear information in docs)
        - Other
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: Describe the behavior you are expecting.
    validations:
      required: false
  - type: textarea
    id: actual
    attributes:
      label: Observed Behavior
      description: Describe the behavior you are observing.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: To Reproduce
      description: Provide steps to reproduce the issue.
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: Fetchd Version
      description: Which version of fetchd were you using? Please enter the version number here.
      placeholder: ex. v0.1.0
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment Details (Optional)
      description: Provide any relevant information about your environment, such as operating system, Python version, and any other libraries used.
      render: markdown
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Failure Logs (Optional)
      description: Include any relevant log snippets or files here. You can paste directly or drag and drop files into this area.
      render: shell
    validations:
        required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional Information (Optional)
      description: Include any screenshots, code snippets, or other relevant details that might help us understand the bug.
      render: markdown
    validations:
      required: false
