name: Build and push images
on:
  push:
    tags:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: |
          docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Publish Public Images
        uses: ejfitzgerald/action-docker-tag@v0.2.0-alpha2
        with:
          repo: fetchai/fetchd
          target: hub

      - name: Setup GCloud
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCLOUD_KEY_IMAGES }}

      - name: Login to GCR Registry
        run: |
          gcloud auth configure-docker

      - name: Build and Publish Private Images
        uses: ejfitzgerald/action-docker-tag@v0.2.0-alpha2
        with:
          repo: gcr.io/fetch-ai-images/fetchd
          target: gcr
