name: Firebase Ephemerial Deployment

on:
  push:
    branches:
      - feature/docs-preview

  pull_request:
    branches:
      - master
    paths:
      - 'docs/**'

jobs:
  build:
    name: Docs Ephemerial Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use python 3.9
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: cd docs && pipenv install

      - name: Build
        run: cd docs && pipenv run mkdocs build

      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: docs

  # deploy:
  #   name: Fronend Ephemerial Deploy
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Download Artifact
  #       uses: actions/download-artifact@master
  #       with:
  #         name: dist
  #         path: services/frontend/build

  #     - uses: FirebaseExtended/action-hosting-deploy@v0
  #       with:
  #         repoToken: "${{ secrets.GITHUB_TOKEN }}"
  #         firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
  #         expires: 1d
  #         projectId: fetch-ai-agent-platform
  #         entryPoint: services/frontend/
  #         target: staging